Vagrant.configure("2") do |config|
  # Ubuntu 2204
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "disknet"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1

    # Добавление пары дисков по 1 ГБ
    vb.customize ["createhd", "--filename", "disk1.vdi", "--size", 1024]
    vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 1, "--device", 0, "--type", "hdd", "--medium", "disk1.vdi"]

    vb.customize ["createhd", "--filename", "disk2.vdi", "--size", 1024]
    vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 2, "--device", 0, "--type", "hdd", "--medium", "disk2.vdi"]
  end

  # Проброс порта HTTP на localhost:8080
  config.vm.network "forwarded_port",
		     guest: 80,
		     host: 8080

  # Провижининг
  config.vm.provision "shell", inline: <<-SHELL
    # Создание точки монтирования
    mkdir -p /mnt/disk1 /mnt/disk2

    # Форматирование дисков, если ещё не отформатированы
    if ! blkid /dev/sdb; then
      mkfs.ext4 /dev/sdb
    fi
    if ! blkid /dev/sdc; then
      mkfs.ext4 /dev/sdc
    fi

    # Монтирование
    mount /dev/sdb /mnt/disk1
    mount /dev/sdc /mnt/disk2

    # Добавление в fstab
    echo '/dev/sdb /mnt/disk1 ext4 defaults 0 0' >> /etc/fstab
    echo '/dev/sdc /mnt/disk2 ext4 defaults 0 0' >> /etc/fstab

    # Установка nginx для проверки проброса порта
    apt-get update
    apt-get install -y nginx

    # Запуск nginx
    systemctl enable nginx
    systemctl start nginx
  SHELL
end
