Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu2204"
  config.vm.hostname = "pam"
  config.vm.network "private_network", ip: "192.168.57.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end

# Разрешение входа по паролю (для проверки PAM)
  config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
    sed -i 's/^#PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
    systemctl restart sshd.service
  SHELL

# Провижининг через Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.verbose = "v"
  end
end
